[package]
name = "bevy_egui_channel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
bevy_egui_channel_macros = { path = "macros" }
enum-iterator = "1.4.1"